apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicea
  namespace: tracing
  labels:
    app: microservicea
    version: v1
    demo: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicea
      version: v1
  template:
    metadata:
      labels:
        app: microservicea
        version: v1
    spec:
      containers:
      - name: microservicea
        image: kaleelcsa/microservice1
        imagePullPolicy: IfNotPresent
        env:
            - name: TRACING_SERVICE
              value: "microserviceA"
            - name: TRACING_PROPAGATION
              value: "b3"
            - name: TRACING_LOG_DASH_SPANS
              value: "true"
            - name: TRACING_PROTOCOL
              value: "udp"
            - name: TRACING_HOST
              value: "jaeger-agent.istio-system"
            - name: TRACING_PORT
              value: "6831"
            - name: serviceb_mp_dash_rest_url
              value: "http://microserviceb:8080/"
        ports:
            - containerPort: 8080
              name: http-8080
              protocol: TCP
